definition:
  title: Enrich IPv4 Addresses
  description: |
    Receive a list of IPv4 addresses and enrich them with additional context
    from multiple threat intelligence sources.
  entrypoint:
    ref: select_ip_addresses
    expects:
      ipv4:
        type: list[str]
        description: A list of IPv4 addresses to enrich
  triggers:
    - type: webhook
      ref: receive_json
      entrypoint: select_ip_addresses
  returns:
    ipv4: list[str]
    reports:
      abuseipdb: ${{ ACTIONS.abuseipdb.result }}
      pulsedive: ${{ ACTIONS.pulsedive.result }}
      shodan: ${{ ACTIONS.shodan.result }}
      virustotal: ${{ ACTIONS.virustotal.result }}

  actions:
    - ref: select_ip_addresses
      action: core.transform.reshape
      args:
        value:
          ipv4: ${{ TRIGGER.ipv4 }}

    - ref: abuseipdb
      action: integrations.abuseipdb.search_ip_address
      depends_on:
        - select_ip_addresses
      for_each: ${{ for var.ip_address in ACTIONS.select_ip_addresses.result }}
      args:
        ip_address: ${{ var.ip_address }}

    - ref: pulsedive
      action: integrations.pulsedive.search_ip_address
      depends_on:
        - select_ip_addresses
      for_each: ${{ for var.ip_address in ACTIONS.select_ip_addresses.result }}
      args:
        ip_address: ${{ var.ip_address }}

    - ref: shodan
      action: integrations.shodan.search_ip_address
      depends_on:
        - select_ip_addresses
      for_each: ${{ for var.ip_address in ACTIONS.select_ip_addresses.result }}
      args:
        ip_address: ${{ var.ip_address }}

    - ref: virustotal
      action: integrations.virustotal.search_ip_address
      depends_on:
        - select_ip_addresses
      for_each: ${{ for var.ip_address in ACTIONS.select_ip_addresses.result }}
      args:
        ip_address: ${{ var.ip_address }}
