definition:
  title: Enrich URLs
  description: |
    Receive a list of URLs and enrich them with additional context
    from multiple threat intelligence sources.
  entrypoint:
    ref: select_urls
    expects:
      urls:
        type: list[str]
        description: A list of URLs to enrich
  triggers:
    - type: webhook
      ref: receive_json
      entrypoint: select_urls
  returns:
    urls: list[str]
    reports:
      alienvault: ${{ ACTIONS.abuseipdb.result }}
      pulsedive: ${{ ACTIONS.pulsedive.result }}
      shodan: ${{ ACTIONS.shodan.result }}
      urlscan: ${{ ACTIONS.urlscan.result }}
      virustotal: ${{ ACTIONS.virustotal.result }}

  actions:
    - ref: select_urls
      action: core.transform.reshape
      args:
        value:
          urls: ${{ TRIGGER.urls }}

    - ref: alienvault
      action: integrations.alienvault.search_url
      depends_on:
        - select_urls
      for_each: ${{ for var.url in ACTIONS.select_urls.result }}
      args:
        url: ${{ var.url }}

    - ref: pulsedive
      action: integrations.pulsedive.search_url
      depends_on:
        - select_urls
      for_each: ${{ for var.url in ACTIONS.select_urls.result }}
      args:
        url: ${{ var.url }}

    - ref: shodan
      action: integrations.shodan.search_url
      depends_on:
        - select_urls
      for_each: ${{ for var.url in ACTIONS.select_urls.result }}
      args:
        url: ${{ var.url }}

    - ref: urlscan
      action: integrations.urlscan.search_url
      depends_on:
        - select_urls
      for_each: ${{ for var.url in ACTIONS.select_urls.result }}
      args:
        url: ${{ var.url }}

    - ref: virustotal
      action: integrations.virustotal.search_url
      depends_on:
        - select_urls
      for_each: ${{ for var.url in ACTIONS.select_urls.result }}
      args:
        url: ${{ var.url }}
