[build-system]
requires = ["hatchling >= 1.27.0"]
build-backend = "hatchling.build"

[project]
name = "tracecat_registry"
description = "Tracecat actions and integrations registry."
readme = "README.md"
requires-python = ">=3.12"
license = "AGPL-3.0"
authors = [{ name = "Tracecat", email = "founders@tracecat.com" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Topic :: Security",
    "Topic :: System :: Systems Administration",
]
dependencies = [
    "aioboto3>=15.0.0",
    "ansible-core>=2.18.0,<3.0.0",
    "ansible-runner==2.4.0",
    "boto3>=1.39.0,<2.0.0",
    "crowdstrike-falconpy==1.5.3",
    "dnspython==2.6.1",
    "docker==7.1.0",
    "duckdb==1.4.3",
    "google-auth==2.48.0",
    "grpcio==1.75.1",
    "grpcio-tools==1.75.1",
    "hatchling==1.27.0",
    "httpx>=0.27.0",
    "jsonpath_ng>=1.7.0,<1.8.0",
    "ldap3==2.9.1",
    "marshmallow==3.26.2",
    "nh3==0.2.18",
    "orjson==3.11.5",
    "paramiko==3.5.0",
    "pydantic>=2.11.7,<3.0.0",
    "pymongo==4.8.0",
    "pyyaml==6.0.3",
    "redis[hiredis]==7.1.0",
    "slack-sdk==3.28.0",
    "sqlalchemy>=2.0.0,<3.0.0",
    "tavily-python==0.7.6",
    "tenacity==8.3.0",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "types-aioboto3[sts,s3]>=15.0.0",
    "types-boto3[sts,s3]>=1.39.0,<2.0.0",
]

[project.urls]
Homepage = "https://tracecat.com"
Documentation = "https://docs.tracecat.com"
Repository = "https://github.com/TracecatHQ/tracecat"

[tool.hatch.version]
path = "tracecat_registry/__init__.py"

[tool.mypy]
strict = true
ignore_missing_imports = true

[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true
