version: "3.8"
services:
  api:
    extends:
      file: docker-compose.yaml
      service: api
    environment:
      TRACECAT__SELF_HOSTED_DB_BACKEND: ${TRACECAT__SELF_HOSTED_DB_BACKEND}
      TRACECAT__DB_URI: ${TRACECAT__DB_URI}
    networks:
      - nginx-network
      - supabase_network_tracecat

  runner:
    extends:
      file: docker-compose.yaml
      service: runner
    environment:
      TRACECAT__SELF_HOSTED_DB_BACKEND: ${TRACECAT__SELF_HOSTED_DB_BACKEND}
      TRACECAT__DB_URI: ${TRACECAT__DB_URI}
    networks:
      - nginx-network
      - supabase_network_tracecat

  nginx:
    extends:
      file: docker-compose.yaml
      service: nginx
    networks:
      - nginx-network
      - supabase_network_tracecat

  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: frontend
  #   restart: unless-stopped
  #   depends_on:
  #     - api
  #   environment:
  #     NEXT_PUBLIC_APP_ENV: "development"
  #     NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
  #     NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
  #     NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
  #     NEXT_PUBLIC_SELF_HOSTED: ${NEXT_PUBLIC_SELF_HOSTED}
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - nginx-network
  #     - supabase_network_tracecat

networks:
  nginx-network:
  supabase_network_tracecat:
    external: true
