{{- include "tracecat.validateRequiredSecrets" . -}}
{{- include "tracecat.validateAuthConfig" . -}}
{{- include "tracecat.validateInfrastructure" . -}}
{{- include "tracecat.validateAutoscaling" . -}}
{{- include "tracecat.validateTemporalAutoscaling" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tracecat.fullname" . }}-api
  labels:
    {{- include "tracecat.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not (default false .Values.api.autoscaling.enabled) }}
  replicas: {{ .Values.api.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tracecat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "tracecat.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
        tracecat.com/access-postgres: "true"
        tracecat.com/access-redis: "true"
      {{- if or .Values.reloader.enabled .Values.podAnnotations }}
      annotations:
        {{- if .Values.reloader.enabled }}
        reloader.stakater.com/auto: "true"
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      serviceAccountName: {{ include "tracecat.serviceAccountName" . }}
      {{- include "tracecat.podScheduling" (dict "root" . "component" "api") | nindent 6 }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ include "tracecat.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            {{- include "tracecat.env.api" . | nindent 12 }}
            {{- include "tracecat.env.secrets.api" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
