apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tracecat.fullname" . }}-executor
  labels:
    {{- include "tracecat.labels" . | nindent 4 }}
    app.kubernetes.io/component: executor
spec:
  replicas: {{ .Values.executor.replicas }}
  selector:
    matchLabels:
      {{- include "tracecat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: executor
  template:
    metadata:
      labels:
        {{- include "tracecat.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: executor
        tracecat.com/access-postgres: "true"
        tracecat.com/access-redis: "true"
      {{- if or .Values.reloader.enabled (and .Values.tracecat.temporal.metrics.enabled .Values.tracecat.temporal.metrics.scrape) .Values.podAnnotations }}
      annotations:
        {{- if .Values.reloader.enabled }}
        reloader.stakater.com/auto: "true"
        {{- end }}
        {{- if and .Values.tracecat.temporal.metrics.enabled .Values.tracecat.temporal.metrics.scrape }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.tracecat.temporal.metrics.port | quote }}
        prometheus.io/path: {{ .Values.tracecat.temporal.metrics.path | default "/metrics" | quote }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      serviceAccountName: {{ include "tracecat.serviceAccountName" . }}
      {{- include "tracecat.podScheduling" (dict "root" . "component" "executor") | nindent 6 }}
      containers:
        - name: executor
          image: "{{ .Values.image.repository }}:{{ include "tracecat.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "-m", "tracecat.executor.worker"]
          {{- if not .Values.tracecat.sandbox.disableNsjail }}
          securityContext:
            privileged: true  # Required for nsjail sandbox mount operations
            capabilities:
              add:
                - SYS_ADMIN  # Required for nsjail sandbox
            seccompProfile:
              type: Unconfined  # Required for nsjail sandbox
          {{- end }}
          {{- if .Values.tracecat.temporal.metrics.enabled }}
          ports:
            - name: metrics
              containerPort: {{ .Values.tracecat.temporal.metrics.port }}
              protocol: TCP
          {{- end }}
          env:
            {{- include "tracecat.env.executor" . | nindent 12 }}
            {{- include "tracecat.env.secrets" . | nindent 12 }}
          volumeMounts:
            - name: sandbox-cache
              mountPath: /var/lib/tracecat/sandbox-cache
            - name: tmp
              mountPath: /tmp
          resources:
            {{- toYaml .Values.executor.resources | nindent 12 }}
      volumes:
        - name: sandbox-cache
          emptyDir: {}
        - name: tmp
          emptyDir: {}
