{{- if .Values.secrets.create.tracecat.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "secrets.create.tracecat.name is required when tracecat secret template is enabled" .Values.secrets.create.tracecat.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "tracecat.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  dbEncryptionKey: {{ required "secrets.create.tracecat.dbEncryptionKey is required when tracecat secret template is enabled" .Values.secrets.create.tracecat.dbEncryptionKey | quote }}
  serviceKey: {{ required "secrets.create.tracecat.serviceKey is required when tracecat secret template is enabled" .Values.secrets.create.tracecat.serviceKey | quote }}
  signingSecret: {{ required "secrets.create.tracecat.signingSecret is required when tracecat secret template is enabled" .Values.secrets.create.tracecat.signingSecret | quote }}
  userAuthSecret: {{ required "secrets.create.tracecat.userAuthSecret is required when tracecat secret template is enabled" .Values.secrets.create.tracecat.userAuthSecret | quote }}
{{- end }}

{{- if .Values.secrets.create.postgres.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "secrets.create.postgres.name is required when postgres secret template is enabled" .Values.secrets.create.postgres.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "tracecat.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  username: {{ required "secrets.create.postgres.username is required when postgres secret template is enabled" .Values.secrets.create.postgres.username | quote }}
  password: {{ required "secrets.create.postgres.password is required when postgres secret template is enabled" .Values.secrets.create.postgres.password | quote }}
  postgres-password: {{ required "secrets.create.postgres.password is required when postgres secret template is enabled" .Values.secrets.create.postgres.password | quote }}
{{- end }}

{{- if .Values.secrets.create.temporalUiOidc.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "secrets.create.temporalUiOidc.name is required when temporal OIDC secret template is enabled" .Values.secrets.create.temporalUiOidc.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "tracecat.labels" . | nindent 4 }}
    app.kubernetes.io/component: temporal
type: Opaque
stringData:
  TEMPORAL_AUTH_CLIENT_ID: {{ required "secrets.create.temporalUiOidc.clientId is required when temporal OIDC secret template is enabled" .Values.secrets.create.temporalUiOidc.clientId | quote }}
  TEMPORAL_AUTH_CLIENT_SECRET: {{ required "secrets.create.temporalUiOidc.clientSecret is required when temporal OIDC secret template is enabled" .Values.secrets.create.temporalUiOidc.clientSecret | quote }}
{{- end }}

{{- if .Values.secrets.create.redis.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "secrets.create.redis.name is required when redis secret template is enabled" .Values.secrets.create.redis.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "tracecat.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
stringData:
  url: {{ required "secrets.create.redis.url is required when redis secret template is enabled" .Values.secrets.create.redis.url | quote }}
{{- end }}
