{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tracecat.serviceAccountName" . }}
  labels:
    {{- include "tracecat.labels" . | nindent 4 }}
  annotations:
    # Create as pre-install hook so it exists before migrations job runs
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/resource-policy": keep
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
