apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tracecat.fullname" . }}-ui
  labels:
    {{- include "tracecat.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      {{- include "tracecat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        {{- include "tracecat.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ui
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- include "tracecat.podScheduling" (dict "root" . "component" "ui") | nindent 6 }}
      containers:
        - name: ui
          image: "{{ .Values.uiImage.repository }}:{{ include "tracecat.uiImageTag" . }}"
          imagePullPolicy: {{ .Values.uiImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            {{- include "tracecat.env.ui" . | nindent 12 }}
            {{- include "tracecat.env.secrets.ui" . | nindent 12 }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
