apiVersion: v1
kind: ConfigMap
metadata:
  name: tracecat-config
data:
  LOG_LEVEL: "INFO"
  TRACECAT__APP_ENV: "production" # not yet configurable, not sure if that would make sense?
  TRACECAT__AUTH_TYPES: "basic,google_oauth" # not yet configurable
  TRACECAT__DB_SSLMODE: "require" # not sure?
  TRACECAT__API_ROOT_PATH: "/api"
  TEMPORAL__CLUSTER_URL: http://temporal-temporal-frontend:7233
  OAUTH_CLIENT_ID: ""
  OAUTH_CLIENT_SECRET: ""
  SMTP_HOST: ""
  SMTP_PORT: ""
  SMTP_STARTTLS_ENABLED: ""
  SMTP_SSL_ENABLED: ""
  SMTP_IGNORE_CERT_ERRORS: "0"
  SMTP_AUTH_ENABLED: "1"
  SMTP_USER: ""
  SMTP_PASS: ""
  LDAP_HOST: ""
  LDAP_PORT: ""
  LDAP_SSL: ""
  LDAP_TYPE: ""
