definition:
  title: List, normalize, and redirect AWS GuardDuty findings.
  description: |
    Pulls AWS GuardDuty findings, normalizes findings into ECS format
    and triggers a child workflow for each finding.
  entrypoint:
    ref: list_guardduty_alerts
    expects:
      interval_minutes: int
      child_workflow_id: str
  triggers:
    - type: webhook
      ref: guardduty_alerts_webhook
      entrypoint: list_guardduty_alerts
  inputs:
    limit: 10
    batch_size: 10

  actions:
    - ref: list_guardduty_alerts
      action: integrations.aws_guardduty.list_guardduty_alerts
      args:
        start_time: ${{ ENV.workflow.start_time }}
        end_time: ${{ ENV.workflow.start_time + FN.minutes(TRIGGER.interval_minutes) }}
        limit: ${{ INPUTS.limit }}

    - ref: normalize_guardduty_alerts
      action: etl.normalization.normalize_events_to_ecs
      depends_on:
        - list_guardduty_alerts
      run_if: ${{ FN.not_empty(ACTIONS.list_guardduty_alerts.result) }}
      args:
        pipeline: https://github.com/elastic/integrations/raw/main/packages/aws/data_stream/guardduty/elasticsearch/ingest_pipeline/default.yml
        data: ${{ ACTION.list_guardduty_alerts.result }}

    - ref: redirect_guardduty_alerts
      action: core.workflow.execute
      depends_on:
        - normalize_guardduty_alerts
      for_each: ${{ for var.alert in ACTIONS.normalize_guardduty_alerts.result }}
      args:
        workflow_id: ${{ TRIGGER.child_workflow_id }}
        loop_strategy: parallel
        fail_strategy: isolated
        batch_size: ${{ INPUTS.batch_size }}
        trigger_inputs:
          title: ${{ var.alert.message }}
          integration: AWS GuardDuty
          alert: ${{ var.alert }}
          severity: ${{ var.alert.aws.guardduty.severity.code }}
