apiVersion: v2
name: tracecat
description: Tracecat is the AI automation platform for mission critical work.
type: application
version: 0.3.17
appVersion: "1.0.0-beta.13"
home: https://tracecat.com
maintainers:
  - email: founders@tracecat.com
    name: Tracecat
    url: https://github.com/tracecathq
sources:
  - https://github.com/tracecathq/tracecat
keywords:
  - ai
  - automation
  - agents
  - workflow
  - open-source
  - python
  - sandbox
dependencies:
  - name: temporal
    version: "1.0.0-rc.1"
    repository: https://go.temporal.io/helm-charts
    condition: temporal.enabled
