definition:
  actions:
    - action: integrations.virustotal.search_url
      args:
        url: ${{ TRIGGER.url_input }}
      depends_on: []
      description: ""
      for_each: null
      ref: search_url
      run_if: null
  config:
    scheduler: dynamic
  description: Virustotal quickstart
  entrypoint:
    expects: {}
    ref: search_url
  variables: {}
  returns: null
  tests: []
  title: Test virustotal
  triggers: []
