name: Frontend code quality

on:
  push:
    branches: ["main"]
    paths:
      - frontend/**
      - tracecat/**
      - packages/**
      - .github/workflows/lint-frontend.yml
  pull_request:
    branches: ["main", "staging"]
    paths:
      - frontend/**
      - tracecat/**
      - packages/**
      - .github/workflows/lint-frontend.yml

permissions:
  contents: read

jobs:
  quality:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install Python dependencies
        run: uv sync --no-install-project

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          working-dir: frontend/
          version: 2.0.4

      - name: Run Biome
        working-directory: frontend
        run: biome ci .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install frontend dependencies
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      - name: Check frontend client is up to date
        run: |
          pnpm -C frontend generate-client-ci
          pnpm -C frontend check
          uv run ruff check . --fix
          uv run ruff format .
          git diff --exit-code frontend/src/client/

      - name: Run TypeScript type check
        working-directory: frontend
        run: pnpm run typecheck
